<link href="/lib/date-picker/css/bootstrap-datepicker3.min.css" rel="stylesheet">
<script src="/lib/date-picker/js/bootstrap-datepicker.min.js"></script>
<style>
    .datepicker {
        border-radius: 0px;
        background: #333;
        color: white;
    }
    .datepicker td:hover,.datepicker th:hover {
        color:white !important;
        background: #265a88 !important;
    }
    .datepicker-dropdown:after {
        border-bottom: 6px solid #333;
    }
    #customer-table-header .row div {
        background: #ddd;
        color: #485563;
        padding: 5px;
        font-weight: bold;
    }
    #customer-table-body .row div {
        border: thin solid #ddd;
        padding-top: 5px;
        padding-bottom: 5px;
    }
    .customer-option {
        width:20px;
        padding: 0px 23px 0px 10px;
        margin-left: 15px;
    }
    .customer-option-header {
        height: 30px;
        padding-right: 30px !important;
    }
    input[type=radio] {
        margin:0px;
    }
    section table {
        background:rgba(0,0,0,0.4);
    }
    .table th {
        background: rgba(0,0,0,0.5);
        color: #66Aefa;
    }
    .table {
        margin-bottom:0px;
    }
    .btn-group {
        margin-bottom:10px;
    }

</style>
<div class="page-header">
    <h1>Accounting<small> - Invoiced Customers</small></h1>
</div>
<div class='col-sm-12'><h4>Choose a date range</h4></div>
<div class="form-inline">
    <div class='col-sm-3'>
        <div class="form-group date">
        <label for="date-time-from">FROM:&nbsp;&nbsp;</label>
            <div class='input-group date' id='date-time-from'>
                <input type='text' class="form-control from"/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-sm-3'>
        <div class="form-group date">
            <label for="date-time-to">TO:&nbsp;&nbsp;</label>
            <div class='input-group date' id='date-time-to'>
                <input type='text' class="form-control to"/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-sm-2'>
        <div class="form-group">
            <div class='input-group date' id='submit-dates'>
                <input type='button' class="btn btn-primary submit" value="Submit"/>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<hr>
<div class="col-sm-12" id="customer-table">
    <div id="customer-table-header">
        <div class="row">
            <div class="col-sm-1 customer-option customer-option-header"></div>
            <div class="col-sm-2">Company Name</div>
            <div class="col-sm-2">Contact Name</div>
            <div class="col-sm-1">Avg. Fee</div>
            <div class="col-sm-1">Trainings</div>
            <div class="col-sm-1">Rep</div>
            <div class="col-sm-1">Type</div>            
        </div>
    </div>
    <div id="customer-table-body">
        <div class="row">
            <div class="col-sm-1 customer-option">
                <input type="radio" name="customer-id" class="customer-id"/>
            </div>
            <div class="col-sm-2">ABP Corporation</div>
            <div class="col-sm-2">Allison Duceat</div>
            <div class="col-sm-1">$70.98</div>
            <div class="col-sm-1">6</div>
            <div class="col-sm-1">GR</div>
            <div class="col-sm-1">CSUB</div>
            <section class="invoice-details col-sm-9 hidden">
                <section class="col-sm-11">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Fee</th>
                            <th># Trainings</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>FSM</td>
                            <td>$45.00</td>
                            <td>6</td>
                            <td>$270.00</td>
                        </tr>
                        <tr>
                            <td>FSRE</td>
                            <td>$30.00</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                        <tr>
                            <td>HACCP</td>
                            <td>$199.00</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                        <tr>
                            <td>FHALL</td>
                            <td>$9.95</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                    </tbody>
                </table>
                <section class="btn-group">
                    <button class="btn btn-primary">Create Invoice</button>
                    <button class="btn btn-success">Mark as Paid</button>
                </section>
                </section>                
            </section>
        </div>
        <div class="row">
            <div class="col-sm-1 customer-option">
                <input type="radio" name="customer-id" class="customer-id"/>
            </div>
            <div class="col-sm-2">ABP Corporation</div>
            <div class="col-sm-2">Allison Duceat</div>
            <div class="col-sm-1">$70.98</div>
            <div class="col-sm-1">6</div>
            <div class="col-sm-1">GR</div>
            <div class="col-sm-1">CSUB</div>
            <section class="invoice-details col-sm-9 hidden">
                <section class="col-sm-11">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Fee</th>
                            <th># Trainings</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>FSM</td>
                            <td>$45.00</td>
                            <td>6</td>
                            <td>$270.00</td>
                        </tr>
                        <tr>
                            <td>FSRE</td>
                            <td>$30.00</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                        <tr>
                            <td>HACCP</td>
                            <td>$199.00</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                        <tr>
                            <td>FHALL</td>
                            <td>$9.95</td>
                            <td>0</td>
                            <td>$0.00</td>
                        </tr>
                    </tbody>
                </table>
                <section class="btn-group">
                    <button class="btn btn-primary">Create Invoice</button>
                    <button class="btn btn-success">Mark as Paid</button>
                </section>
                </section>                
            </section>
        </div>
    </div>
<div>
</div>
<div class="clearfix"></div>
<script>
    $('#date-time-from input').datepicker({
        autoclose: true
    });
    $('#date-time-to input').datepicker({
        autoclose: true
    });
    $('.customer-id').click(function(){
        $('.active-invoice').addClass('hidden');
        $('.active-invoice').removeClass('active-invoice');
        $(this).parent('.customer-option').parent('.row').find('.invoice-details').addClass('active-invoice');
        $(this).parent('.customer-option').parent('.row').find('.invoice-details').removeClass('hidden');
    });
    
    $('.submit').click(function(e){
        var from = $('.from').val();
        var to = $('.to').val();

        if(from.length == 0 || to.length == 0 || from > to)
        {
            alert('Please select a valid date range.');
            return;
        }
        var data = {
            'from': $('#date-time-from').val(),
            'to': $('#date-time-to').val(),
        }
        $.ajax({
            type: 'post',
            url: '/accounting/invoiced-customers/list',
            data: data,
            dataType: 'json',
            success: function(response)
            {
                loadInvoiceTable(response);
            }
        });
    });

    function loadInvoiceTable(data)
    {
        $('#accounts tbody').html('');
        if(data.length == 0)
            $('.table-msg').html('No invoices found matching your criteria.');
        else
            $('.table-msg').html('');
        
        $(data).each(function(){
            /*var $row = $('<tr></tr>');//<td></td>
            $row.append('<td class="account-opt"><input type="radio" name="account" value="'+this.AccountName+'" class="account-option"/></td>');
            $row.append('<td class="account-name">'+this.AccountName+'</td>');
            $row.append('<td class="company-name">'+this.CompanyName+'</td>');
            $row.append('<td class="contact-name">'+this.ContactName+'</td>');
            $('#accounts tbody').append($row);*/
        });
    }
</script>